### ISSUE TITLE
every seems correct and yet the stream does not appear in the html page 

### ISSUE THREAD

**Issue by desreumaux** [aaronprisk/foss-video-configs#1]
every seems correct and yet the stream does not appear in the html page 

OBS + nginx on Ubuntu server IP 192.168.2.15
html page on Windows 10 in the same network

**nginx.conf :**

load_module "modules/ngx_rtmp_module.so";
user stream;
worker_processes  auto;
events {
    worker_connections  1024;
}

# RTMP configuration
rtmp {
    server {
        listen 1935; # Listen on standard RTMP port
        chunk_size 4000;

        application live {
            live on;
            # Turn on HLS
            hls on;
            hls_path /mnt/hls/;
            hls_fragment 3;
            hls_playlist_length 60;
            # disable consuming the stream from nginx as rtmp
            deny play all;
        }
    }
}

http {
    sendfile off;
    tcp_nopush on;
    directio 512;
    default_type application/octet-stream;

    # VideoJS Player
    server {
	    include	mime.types;
            	listen       80;
            	server_name  EXAMPLE.ORG;
	    location / {
	    root    /var/www/html/;
	    index    index.html index.htm;
	    }
    }

    server {
        listen 8080;

        location / {
            # Disable cache
            add_header 'Cache-Control' 'no-cache';

            # CORS setup
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';

            # allow CORS preflight requests
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            types {
                application/dash+xml mpd;
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            root /mnt/;
        }
    }
}

**index.html :**

![indexhtml](https://user-images.githubusercontent.com/77922349/115161674-4dc60780-a09f-11eb-8371-1457d323d6c9.JPG)

</body>
</html><!DOCTYPE html>
<html>
<head>
  <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />

  
  <!script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>
<body>
  <video
    id="my-video"
    class="video-js vjs-big-play-centered"
    controls
    preload="auto"
    width="900"
    height="600"
    poster="ABC.jpg"
    data-setup="{}"
  >
   <source src="http://192.168.2.15:8080/hls/stream.m3u8" type="application/x-mpegURL" />
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a
      web browser that
      <!a href="https://videojs.com/html5-video-support/" target="_blank"
        >supports HTML5 video</a
        >
    </p>
  </video>

Records in /mnt/hls
![Capture d’écran du 2021-04-18 19-38-47](https://user-images.githubusercontent.com/77922349/115161123-1d309e80-a09c-11eb-86cc-b2c28d5515fe.png)

settings OBS
![Capture d’écran du 2021-04-18 19-40-51](https://user-images.githubusercontent.com/77922349/115161128-23267f80-a09c-11eb-8ccf-95250cef8725.png)

**result on the html page during the stream ( javascript is active in the browser )**
![video](https://user-images.githubusercontent.com/77922349/115161136-31749b80-a09c-11eb-96e7-f657238a39c8.JPG)

**POSTER :**
![ABC](https://user-images.githubusercontent.com/77922349/115161143-3b969a00-a09c-11eb-8f0a-be15f11c13f8.JPG)

Thank you in advance for a little indication to help me locate the problem
regards
Jacques DESREUMAUX
FRANCE

**Comment by aaronprisk** [comment]
Hello Jacques,
Could you please bring up the Inspect Element tool in Firefox or Chrome > Select Console > Try to play the stream and then share any error messages you receive.

**Comment by desreumaux** [comment]
hello,
here is the result carried out directly on the Ubuntu server via firefox which eliminates any problem with port 8080.
NB : the POSTER has not been transferred to this server
regards
Jacques

![Capture d’écran du 2021-04-19 17-21-33](https://user-images.githubusercontent.com/77922349/115267119-1ad05200-a139-11eb-8181-a2815deaf650.png)

**Comment by aaronprisk** [comment]
Thank you for providing some more information. 
Two quick points of clarification:
1) I see from your terminal screenshot that your stream key was "m3u8", but your video.js player is set to play a stream with the key "stream". 

2)  Can you also confirm that the www user and group are the owner of the /mnt/hls directory.

**Comment by desreumaux** [comment]
hello,
first of all thank you for your quick answers
1) in index.html i modified   stream.m3u8   by   STREAM-KEY.m3u8
2) as there is no www account i used root:root for /mnt/hls
3) i am logged in with the "stream" account which does not have the rights of the super user raison why i declare   user stream;   at the beginning of the nginx.conf file.
Here are all screenshots after these modifications, but the stream still does not appear in the browser.
regards
Jacques

![Capture d’écran du 2021-04-20 16-43-17](https://user-images.githubusercontent.com/77922349/115427597-e4123e80-a201-11eb-9ccd-dc4d238bda88.png)

![Capture d’écran du 2021-04-20 16-44-22](https://user-images.githubusercontent.com/77922349/115427632-ed9ba680-a201-11eb-9ff6-82ddd0bfaa14.png)

![Capture d’écran du 2021-04-20 16-46-07](https://user-images.githubusercontent.com/77922349/115427695-f9876880-a201-11eb-9353-f205e9bdfdec.png)

![Capture d’écran du 2021-04-20 16-46-33](https://user-images.githubusercontent.com/77922349/115427730-03a96700-a202-11eb-9408-61a05b4922ac.png)

![Capture d’écran du 2021-04-20 17-06-20](https://user-images.githubusercontent.com/77922349/115427767-0c9a3880-a202-11eb-80de-694267b6bf2f.png)

![Capture d’écran du 2021-04-20 17-13-52](https://user-images.githubusercontent.com/77922349/115427804-1459dd00-a202-11eb-96e8-aee9002b8f9b.png)

![Capture d’écran du 2021-04-20 17-14-58](https://user-images.githubusercontent.com/77922349/115427872-1fad0880-a202-11eb-81ed-afe664749281.png)

![Capture d’écran du 2021-04-20 17-20-45](https://user-images.githubusercontent.com/77922349/115427908-29cf0700-a202-11eb-81f0-e286b1a4b540.png)

**Comment by aaronprisk** [comment]
I see. Can you change the owner of /mnt/hls to that stream user account, and see if that fixes your problem?

**Comment by desreumaux** [comment]
hello,
that does not change.
tests carried out on localhost and directly on the IP of the machine
here is the result
regards
Jacques

![Capture d’écran du 2021-04-20 19-32-17](https://user-images.githubusercontent.com/77922349/115440535-20e53200-a210-11eb-84b3-8214173d166d.png)

**Comment by desreumaux** [comment]
new test with horodatage

![Capture d’écran du 2021-04-20 19-55-30](https://user-images.githubusercontent.com/77922349/115442775-b681c100-a212-11eb-858c-e7af542dfb5a.png)

**Comment by aaronprisk** [comment]
Just for clarification, is this the console output after clicking the Play button on the video.js player?

I ask because I'm not seeing the typical errors I usually see when there is some kind of stream or permission related problem.

**Comment by desreumaux** [comment]
yes I clicked on the two buttons the one that appears in the center then the one that is at the bottom left
regards
Jacques

**Comment by desreumaux** [comment]
hello,
in order :
I turn on the ubuntu server
logging: stream + password
run OBS Studio
start the stream
run Firefox
access to 127.0.0.1
the video player opens
I click on the play buttons
I open the Firefox console
I check that the segments register well in / mnt / hls
I take a screenshot of the whole.

![Capture d’écran du 2021-04-21 17-42-41](https://user-images.githubusercontent.com/77922349/115583836-8d246c00-a2ca-11eb-9b41-d4f982c5a092.png)

**Comment by desreumaux** [comment]
when the OBS stream is in progress
segments that are stored in / mnt / hls are named:  test-x.ts
the segment being recorded is named:  test.m3u8
i guess this is normal.
after stopping the stream the records gradually disappear from / mnt / hls
i also guess this is normal

![Capture d’écran du 2021-04-21 18-00-05](https://user-images.githubusercontent.com/77922349/115586693-26548200-a2cd-11eb-81b2-372fe1c07932.png)

regards
Jacques

**Comment by aaronprisk** [comment]
That is correct. HLS creates an index file - .m3u8 and the video chunks - .ts according to the settings in the nginx.conf.

I was looking at your earlier screenshots and in your player html it seems to be missing the closing video.js script near the end of the body.

EX:
<script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>

Can you confirm that line exists on your player page?

**Comment by desreumaux** [comment]
after insert the line 

![Capture d’écran du 2021-04-21 19-58-04](https://user-images.githubusercontent.com/77922349/115599855-55bebb00-a2dc-11eb-9a7e-cc3e2509798b.png)

**Comment by desreumaux** [comment]
Hello,

everything works with the following Html file retrieved from the videojs.com site
regards
Jacques


<!DOCTYPE html>
<html>
<head>
  <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />

  
  
</head>

<body>
  <video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="1280"
    height="720"
    poster="ABC.jpg"
    data-setup="{}"
  >
    <source src="http://192.168.2.15:8080/hls/test.m3u8"
    type="application/x-mpegURL" />
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a
      web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank"
        >supports HTML5 video</a
      >
    </p>
  </video>

  <script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>
</body>
</html>

**Comment by desreumaux** [comment]
<!DOCTYPE html>
<html>
<head>
  <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />

  
  
</head>

<body>
  <video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="1280"
    height="720"
    poster="ABC.jpg"
    data-setup="{}"
  >
    <source src="http://192.168.2.15:8080/hls/test.m3u8"
    type="application/x-mpegURL" />
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a
      web browser that
      <a href="https://videojs.com/html5-video-support/" target="_blank"
        >supports HTML5 video</a
      >
    </p>
  </video>

  <script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>
</body>
</html>

**Comment by aaronprisk** [comment]
Great to hear! I just updated the line in the player.html.

**Comment by desreumaux** [comment]
here is the full content of the index.html file

![55923189-03B5-4571-BBD5-578EB4919B84](https://user-images.githubusercontent.com/77922349/115963980-695b6300-a522-11eb-9586-53329296fdc1.png)
